name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Makefile Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Go Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.0

      - name: Add GOPATH/bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build with Makefile
        run: make build

      - name: Test with Makefile
        run: make test

      - name: Lint with Makefile
        run: make lint

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: makefile-test-results
          path: test-report.xml
          retention-days: 5
